/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents a single change action performed on an attribute. For tag attributes, includes additional id and value fields.
 * @export
 * @interface AttributeChangeAction
 */
export interface AttributeChangeAction {
    /**
     * The type of change action performed.
     * @type {string}
     * @memberof AttributeChangeAction
     */
    'action': AttributeChangeActionActionEnum;
    /**
     * The ID of the item when the attribute is \'tags\'.  This field is only present for tag-related changes.
     * @type {string}
     * @memberof AttributeChangeAction
     */
    'id'?: string;
    /**
     * The value of the item when the attribute is \'tags\'.  This field is only present for tag-related changes.
     * @type {string}
     * @memberof AttributeChangeAction
     */
    'value'?: string;
}

export const AttributeChangeActionActionEnum = {
    Added: 'ADDED',
    Removed: 'REMOVED',
    Changed: 'CHANGED'
} as const;

export type AttributeChangeActionActionEnum = typeof AttributeChangeActionActionEnum[keyof typeof AttributeChangeActionActionEnum];


