/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ContactCustomAttribute } from './contact-custom-attribute';

/**
 * Represents a contact.
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * Unique ID for the object.
     * @type {string}
     * @memberof Contact
     */
    'id': string;
    /**
     * Contact\'s nickname.
     * @type {string}
     * @memberof Contact
     */
    'nickname'?: string;
    /**
     * Two-letter country abbreviation. See [ISO 3166-1 alpha-2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
     * @type {string}
     * @memberof Contact
     */
    'countryCode'?: string;
    /**
     * Full country name.
     * @type {string}
     * @memberof Contact
     */
    'countryName'?: string;
    /**
     * Unique Phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.
     * @type {string}
     * @memberof Contact
     */
    'phoneNumber'?: string;
    /**
     * The contact\'s email address. If present, the email address must be unique.
     * @type {string}
     * @memberof Contact
     */
    'email'?: string;
    /**
     * The time at which the latest inbound message was created, formatted in [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339). e.g., `2022-06-01T12:00:00.000Z`.
     * @type {string}
     * @memberof Contact
     */
    'lastSeen'?: string;
    /**
     * Contact\'s tags.
     * @type {Array<string>}
     * @memberof Contact
     */
    'tags'?: Array<string>;
    /**
     * The time at which the contact was created, formatted in [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339). e.g., `2022-06-01T12:00:00.000Z`.
     * @type {string}
     * @memberof Contact
     */
    'createTime'?: string;
    /**
     * Contact\'s custom attributes.
     * @type {Array<ContactCustomAttribute>}
     * @memberof Contact
     */
    'customAttributes'?: Array<ContactCustomAttribute>;
}

