/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 联系人来源类型的枚举值。此为内部类型标识，非页面显示名称。 每个枚举值对应的显示名称如下： - WHATSAPP: \"Inbound message\" - GROWTH_TOOL: \"Link/QR Code\" - MANUALLY_ADDED: \"Manually added\" - FILE_IMPORT: \"File import\" - SHOPIFY: \"Shopify\" - API: \"API added\" - AD: \"AD\" - POST: \"Post\" - CALLING: \"Calling\" - SMB: \"Whatsapp Business App\" - UNKNOWN: \"Unknown\"
 * @export
 * @enum {string}
 */

export const ContactSourceType = {
    Whatsapp: 'WHATSAPP',
    GrowthTool: 'GROWTH_TOOL',
    ManuallyAdded: 'MANUALLY_ADDED',
    FileImport: 'FILE_IMPORT',
    Shopify: 'SHOPIFY',
    Api: 'API',
    Ad: 'AD',
    Post: 'POST',
    Calling: 'CALLING',
    Smb: 'SMB',
    Unknown: 'UNKNOWN'
} as const;

export type ContactSourceType = typeof ContactSourceType[keyof typeof ContactSourceType];



