/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AttributeChangeAction } from './attribute-change-action';
import { ContactAttributeChangeNewValue } from './contact-attribute-change-new-value';
import { ContactAttributeChangeOldValue } from './contact-attribute-change-old-value';

/**
 * Represents a single attribute change, containing the old value, new value, and change actions.
 * @export
 * @interface ContactAttributeChange
 */
export interface ContactAttributeChange {
    /**
     * 
     * @type {ContactAttributeChangeOldValue}
     * @memberof ContactAttributeChange
     */
    'oldValue'?: ContactAttributeChangeOldValue;
    /**
     * 
     * @type {ContactAttributeChangeNewValue}
     * @memberof ContactAttributeChange
     */
    'newValue'?: ContactAttributeChangeNewValue;
    /**
     * An array of change actions that describe what operations were performed on this attribute.
     * @type {Array<AttributeChangeAction>}
     * @memberof ContactAttributeChange
     */
    'extra'?: Array<AttributeChangeAction>;
}

