/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents a contact attribute configuration. Contains information about the attribute\'s metadata and available values.
 * @export
 * @interface ContactAttribute
 */
export interface ContactAttribute {
    /**
     * Unique identifier for the contact attribute.
     * @type {string}
     * @memberof ContactAttribute
     */
    'id': string;
    /**
     * Display name of the contact attribute.
     * @type {string}
     * @memberof ContactAttribute
     */
    'name': string;
    /**
     * Key name used to reference this attribute.
     * @type {string}
     * @memberof ContactAttribute
     */
    'key': string;
    /**
     * Data type of the contact attribute.
     * @type {string}
     * @memberof ContactAttribute
     */
    'type': ContactAttributeTypeEnum;
    /**
     * Description of the contact attribute.
     * @type {string}
     * @memberof ContactAttribute
     */
    'desc'?: string;
    /**
     * Array of possible values for this attribute. Only present when type is \"ARRAY\".
     * @type {Array<string>}
     * @memberof ContactAttribute
     */
    'values'?: Array<string>;
}

export const ContactAttributeTypeEnum = {
    Boolean: 'BOOLEAN',
    Text: 'TEXT',
    Time: 'TIME',
    Array: 'ARRAY'
} as const;

export type ContactAttributeTypeEnum = typeof ContactAttributeTypeEnum[keyof typeof ContactAttributeTypeEnum];


