/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AttributeChangeAction } from './attribute-change-action';

/**
 * Represents a single attribute change, containing the old value, new value, and change actions.
 * @export
 * @interface ContactAttributeChange
 */
export interface ContactAttributeChange {
    /**
     * The previous value of the attribute before the change. Can be a string, number, array, or boolean depending on the attribute type. This field is not included when the value is null.
     * @type {any}
     * @memberof ContactAttributeChange
     */
    'oldValue'?: any;
    /**
     * The new value of the attribute after the change. Can be a string, number, array, or boolean depending on the attribute type. This field is not included when the value is null.
     * @type {any}
     * @memberof ContactAttributeChange
     */
    'newValue'?: any;
    /**
     * An array of change actions that describe what operations were performed on this attribute.
     * @type {Array<AttributeChangeAction>}
     * @memberof ContactAttributeChange
     */
    'extra'?: Array<AttributeChangeAction>;
}

