/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomEventDefinitionPropertyCreateRequest } from './custom-event-definition-property-create-request';

/**
 * Contains the properties of the custom event definition to be created.
 * @export
 * @interface CustomEventDefinitionCreateRequest
 */
export interface CustomEventDefinitionCreateRequest {
    /**
     * The unique name of the custom event.
     * @type {string}
     * @memberof CustomEventDefinitionCreateRequest
     */
    'name': string;
    /**
     * The label of the custom event.
     * @type {string}
     * @memberof CustomEventDefinitionCreateRequest
     */
    'label': string;
    /**
     * The description of the event.
     * @type {string}
     * @memberof CustomEventDefinitionCreateRequest
     */
    'description'?: string;
    /**
     * Type of the object that the event will be associated with. - `CONTACT`: Indicates that the object is a `contact`.
     * @type {string}
     * @memberof CustomEventDefinitionCreateRequest
     */
    'objectType': CustomEventDefinitionCreateRequestObjectTypeEnum;
    /**
     * A list of property definitions for the event.
     * @type {Array<CustomEventDefinitionPropertyCreateRequest>}
     * @memberof CustomEventDefinitionCreateRequest
     */
    'properties'?: Array<CustomEventDefinitionPropertyCreateRequest>;
}

export const CustomEventDefinitionCreateRequestObjectTypeEnum = {
    Contact: 'CONTACT'
} as const;

export type CustomEventDefinitionCreateRequestObjectTypeEnum = typeof CustomEventDefinitionCreateRequestObjectTypeEnum[keyof typeof CustomEventDefinitionCreateRequestObjectTypeEnum];


