/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Contains the properties of the custom event definition to be updated.
 * @export
 * @interface CustomEventDefinitionUpdateRequest
 */
export interface CustomEventDefinitionUpdateRequest {
    /**
     * The label of the event definition.
     * @type {string}
     * @memberof CustomEventDefinitionUpdateRequest
     */
    'label'?: string;
    /**
     * The description of the event definition.
     * @type {string}
     * @memberof CustomEventDefinitionUpdateRequest
     */
    'description'?: string;
}

