/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EmailContentType } from './email-content-type';

/**
 * 
 * @export
 * @interface EmailSendRequest
 */
export interface EmailSendRequest {
    /**
     * - The sender\'s email. Its domain should be one that has been registered and activated in your YCloud account. - The test address provided by YCloud is `ycloud@ycloud-mail.com`, which only supports sending emails to your registered email address. - The sender\'s email address is required while the sender\'s name is optional. For example, both `ycloud@ycloud-mail.com` and `YCloud<ycloud@ycloud-mail.com>` work.
     * @type {string}
     * @memberof EmailSendRequest
     */
    'from': string;
    /**
     * - The intended recipients\' email addresses. - Supports a comma-separated list of one or more addresses. Max items: 100.
     * @type {string}
     * @memberof EmailSendRequest
     */
    'to': string;
    /**
     * The email subject, which contains a short string identifying the topic of the message. Max length: 255.
     * @type {string}
     * @memberof EmailSendRequest
     */
    'subject': string;
    /**
     * - The email body. Max size: 150 KB. - Variables in the form of `#var_1#` are supported, they should be used together with the `variables` parameter. Variable keys only support letters, digits, and the underline character (`_`). - You can use the [Test Templates](https://help.ycloud.com/en/articles/6006545) provided by YCloud for testing.
     * @type {string}
     * @memberof EmailSendRequest
     */
    'content': string;
    /**
     * 
     * @type {EmailContentType}
     * @memberof EmailSendRequest
     */
    'contentType'?: EmailContentType;
    /**
     * - The variable key-value pairs that will replace the variable placeholders in `content` for each recipient. Variable keys are those that are wrapped with `#` as placeholders (e.g., `#var_1#`) in `content`. The placeholders will be replaced by variable values when sending the email. - The size of the array must be the same as the number of recipients in `to`. Be aware that `cc` and `bcc` addresses are excluded, and they can not receive emails that contain variables. - This parameter\'s size will be calculated together with the parameter `content`. The whole size must not exceed 150 KB.
     * @type {Array<{ [key: string]: string; }>}
     * @memberof EmailSendRequest
     */
    'variables'?: Array<{ [key: string]: string; }>;
    /**
     * Recipients who will receive a copy of the email.
     * @type {string}
     * @memberof EmailSendRequest
     */
    'cc'?: string;
    /**
     * Recipients who will receive a blind carbon copy of the email.
     * @type {string}
     * @memberof EmailSendRequest
     */
    'bcc'?: string;
    /**
     * If this field exists, then the reply should go to the addresses indicated in that field and not to the address(es) indicated in the `from` field.
     * @type {string}
     * @memberof EmailSendRequest
     */
    'replyTo'?: string;
    /**
     * This is a summary of your email. Max length: 70.
     * @type {string}
     * @memberof EmailSendRequest
     */
    'summary'?: string;
    /**
     * A unique string to reference the object. This can be an order number or similar, and can be used to reconcile the object with your internal systems.
     * @type {string}
     * @memberof EmailSendRequest
     */
    'externalId'?: string;
    /**
     * Delivery report URL. You can provide a URL, and we will push the updated status report to your server in time. e.g., https://httpbin.org/anything?tag=api. Note: We recommend configuring Webhook Endpoints instead.
     * @type {string}
     * @memberof EmailSendRequest
     */
    'callbackUrl'?: string;
}

