/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents event property configuration for webhook endpoints. Specifies which properties should be included in the webhook payload for a specific event type.
 * @export
 * @interface EventProperty
 */
export interface EventProperty {
    /**
     * The event type for which properties are configured. This field accepts any valid event type that supports property configuration.
     * @type {string}
     * @memberof EventProperty
     */
    'event': string;
    /**
     * A list of property names that should be included in the webhook payload for the specified event type. The available properties depend on the specific event type configured.
     * @type {Array<string>}
     * @memberof EventProperty
     */
    'properties': Array<string>;
}

