/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of event.
 * @export
 * @enum {string}
 */

export const EventType = {
    /**
    * Occurs when an email delivery status is updated, and the status changes to &#x60;delivered&#x60; or &#x60;failed&#x60;.
    */
    EmailDeliveryUpdated: 'email.delivery.updated',
    /**
    * Occurs when an SMS message status is updated, and the status changes to &#x60;delivered&#x60; or &#x60;undelivered&#x60;.
    */
    SmsMessageUpdated: 'sms.message.updated',
    /**
    * Occurs when an SMS inbound message is received, which means a user replies to your message.
    */
    SmsInboundReceived: 'sms.inbound.received',
    /**
    * Occurs when a voice message status is updated, and the status changes to &#x60;delivered&#x60; or &#x60;undelivered&#x60;.
    */
    VoiceMessageUpdated: 'voice.message.updated',
    /**
    * Occurs when a WhatsApp Business Account is deleted.
    */
    WhatsappBusinessAccountDeleted: 'whatsapp.business_account.deleted',
    /**
    * Occurs when a WhatsApp Business Account has been reviewed.
    */
    WhatsappBusinessAccountReviewed: 'whatsapp.business_account.reviewed',
    /**
    * Occurs when a policy violation happened, WhatsApp Business Account has been banned and more.
    */
    WhatsappBusinessAccountUpdated: 'whatsapp.business_account.updated',
    /**
    * Occurs when a WhatsApp inbound message is received.
    */
    WhatsappInboundMessageReceived: 'whatsapp.inbound_message.received',
    /**
    * Occurs when a WhatsApp outbound message status is updated, and the status changes to &#x60;sent&#x60;, &#x60;failed&#x60;, &#x60;delivered&#x60;, or &#x60;read&#x60;.
    */
    WhatsappMessageUpdated: 'whatsapp.message.updated',
    /**
    * Occurs when a WhatsApp business phone number is deleted.
    */
    WhatsappPhoneNumberDeleted: 'whatsapp.phone_number.deleted',
    /**
    * Occurs when a WhatsApp business phone number&#39;s name has been approved or rejected.
    */
    WhatsappPhoneNumberNameUpdated: 'whatsapp.phone_number.name_updated',
    /**
    * Occurs when a WhatsApp business phone number&#39;s quality-related status is updated, and the status changes to &#x60;GREEN&#x60;, &#x60;YELLOW&#x60;, or &#x60;RED&#x60;.
    */
    WhatsappPhoneNumberQualityUpdated: 'whatsapp.phone_number.quality_updated',
    /**
    * Occurs when a WhatsApp template category is updated.
    */
    WhatsappTemplateCategoryUpdated: 'whatsapp.template.category_updated',
    /**
    * Occurs when a WhatsApp template quality rating is updated.
    */
    WhatsappTemplateQualityUpdated: 'whatsapp.template.quality_updated',
    /**
    * Occurs when a WhatsApp template status is updated, and the status changes to &#x60;REJECTED&#x60;, &#x60;APPROVED&#x60;, &#x60;PAUSED&#x60;, &#x60;DISABLED&#x60;, or &#x60;IN_APPEAL&#x60;.
    */
    WhatsappTemplateReviewed: 'whatsapp.template.reviewed'
} as const;

export type EventType = typeof EventType[keyof typeof EventType];



