/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SmsSendRequest
 */
export interface SmsSendRequest {
    /**
     * The recipient\'s phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.
     * @type {string}
     * @memberof SmsSendRequest
     */
    'to': string;
    /**
     * The text of this message.
     * @type {string}
     * @memberof SmsSendRequest
     */
    'text': string;
    /**
     * [Sender ID](https://help.ycloud.com/en/articles/3080386) to be used.
     * @type {string}
     * @memberof SmsSendRequest
     */
    'senderId'?: string;
    /**
     * This parameter is only required for Chinese mainland SMSs. You must specify an approved signature such as `YCloud`. It will be added to the beginning of SMS body and wrapped with `【】`, e.g. `【YCloud】Your verification code is 123456`.
     * @type {string}
     * @memberof SmsSendRequest
     */
    'signature'?: string;
    /**
     * A unique string to reference the object. This can be an order number or similar, and can be used to reconcile the object with your internal systems.
     * @type {string}
     * @memberof SmsSendRequest
     */
    'externalId'?: string;
    /**
     * Delivery report URL. You can provide a URL, and we will push the updated status report to your server in time. e.g., https://httpbin.org/anything?tag=api. Note: We recommend configuring Webhook Endpoints instead.
     * @type {string}
     * @memberof SmsSendRequest
     */
    'callbackUrl'?: string;
}

