/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UnsubscriberChannel } from './unsubscriber-channel';
import { UnsubscriberType } from './unsubscriber-type';

/**
 * 
 * @export
 * @interface UnsubscriberCreateRequest
 */
export interface UnsubscriberCreateRequest {
    /**
     * 
     * @type {UnsubscriberType}
     * @memberof UnsubscriberCreateRequest
     */
    'type': UnsubscriberType;
    /**
     * The customer who has opted out. For `type=PHONE_NUMBER`, it should be a phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.
     * @type {string}
     * @memberof UnsubscriberCreateRequest
     */
    'customer': string;
    /**
     * 
     * @type {UnsubscriberChannel}
     * @memberof UnsubscriberCreateRequest
     */
    'channel': UnsubscriberChannel;
    /**
     * The customer\'s region code, formatted in [ISO 3166-1 alpha-2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
     * @type {string}
     * @memberof UnsubscriberCreateRequest
     */
    'regionCode'?: string;
}

