/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Contains information about verification fallback. For example, you can enable sms fallback for WhatsApp verification messages.
 * @export
 * @interface VerificationFallback
 */
export interface VerificationFallback {
    /**
     * Whether this fallback you requested is supported. If `false` is returned, it means that there are errors for this fallback, and this fallback will not be triggered.
     * @type {boolean}
     * @memberof VerificationFallback
     */
    'supported'?: boolean;
    /**
     * The reason why the fallback is unsupported, e.g, `PARAM_INVALID`, `SMS_SIGNATURE_UNAVAILABLE`, `SENDER_ID_UNAVAILABLE`, or `MESSAGING_REGION_UNSUPPORTED`.
     * @type {string}
     * @memberof VerificationFallback
     */
    'unsupportedReason'?: string;
    /**
     * The detail message why the fallback is unsupported.
     * @type {string}
     * @memberof VerificationFallback
     */
    'unsupportedDetail'?: string;
}

