/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageInteractiveActionButtonsInner } from './whatsapp-message-interactive-action-buttons-inner';
import { WhatsappMessageInteractiveActionSectionsInner } from './whatsapp-message-interactive-action-sections-inner';

/**
 * [WhatsApp Interactive Action Object](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#action-object).
 * @export
 * @interface WhatsappMessageInteractiveAction
 */
export interface WhatsappMessageInteractiveAction {
    /**
     * Required for Reply Buttons.
     * @type {Array<WhatsappMessageInteractiveActionButtonsInner>}
     * @memberof WhatsappMessageInteractiveAction
     */
    'buttons'?: Array<WhatsappMessageInteractiveActionButtonsInner>;
    /**
     * Required for List Messages. Button content. It cannot be an empty string and must be unique within the message. Emojis are supported, markdown is not.
     * @type {string}
     * @memberof WhatsappMessageInteractiveAction
     */
    'button'?: string;
    /**
     * Required for List Messages.
     * @type {Array<WhatsappMessageInteractiveActionSectionsInner>}
     * @memberof WhatsappMessageInteractiveAction
     */
    'sections'?: Array<WhatsappMessageInteractiveActionSectionsInner>;
}

