/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Use for `location` messages. See also [WhatsApp Location Object](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#location-object).
 * @export
 * @interface WhatsappMessageLocation
 */
export interface WhatsappMessageLocation {
    /**
     * Latitude of the location.
     * @type {number}
     * @memberof WhatsappMessageLocation
     */
    'latitude': number;
    /**
     * Longitude of the location.
     * @type {number}
     * @memberof WhatsappMessageLocation
     */
    'longitude': number;
    /**
     * Name of the location.
     * @type {string}
     * @memberof WhatsappMessageLocation
     */
    'name'?: string;
    /**
     * Address of the location. Only displayed if `name` is present.
     * @type {string}
     * @memberof WhatsappMessageLocation
     */
    'address'?: string;
}

