/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Required if `flow_action` is `navigate`. Should be omitted otherwise.
 * @export
 * @interface WhatsappMessageInteractiveActionParametersFlowActionPayload
 */
export interface WhatsappMessageInteractiveActionParametersFlowActionPayload {
    /**
     * The ID of the screen displayed first. It needs to be an **entry** screen.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionParametersFlowActionPayload
     */
    'screen'?: string;
    /**
     * Optional input data for the first screen of the Flow. If provided, this must be a non-empty object.
     * @type {{ [key: string]: object; }}
     * @memberof WhatsappMessageInteractiveActionParametersFlowActionPayload
     */
    'data'?: { [key: string]: object; };
}

