/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Indicates who initiated the conversation. `business_initiated`: Indicates that the conversation started by a business sending the first message to a customer. This applies any time it has been more than 24 hours since the last customer message. `user_initiated`: Indicates that the conversation started by a business replying to a customer message. This applies only when the business reply is within 24 hours of the last customer message. `referral_conversion`: Indicates that the conversation originated from a free entry point. These conversations are always customer-initiated.
 * @export
 * @enum {string}
 */

export const WhatsappConversationOriginType = {
    /**
    * Indicates that the conversation started by a business sending the first message to a customer. This applies any time it has been more than 24 hours since the last customer message.
    */
    BusinessInitiated: 'business_initiated',
    /**
    * Indicates that the conversation started by a business replying to a customer message. This applies only when the business reply is within 24 hours of the last customer message.
    */
    UserInitiated: 'user_initiated',
    /**
    * Indicates that the conversation originated from a free entry point. These conversations are always customer-initiated.
    */
    ReferralConversion: 'referral_conversion'
} as const;

export type WhatsappConversationOriginType = typeof WhatsappConversationOriginType[keyof typeof WhatsappConversationOriginType];



