/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageOrderPaymentGateway } from './whatsapp-message-order-payment-gateway';

/**
 * Payment settings for the order.
 * @export
 * @interface WhatsappMessageOrderPaymentSetting
 */
export interface WhatsappMessageOrderPaymentSetting {
    /**
     * Must be set to `payment_gateway`.
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSetting
     */
    'type': string;
    /**
     * 
     * @type {WhatsappMessageOrderPaymentGateway}
     * @memberof WhatsappMessageOrderPaymentSetting
     */
    'payment_gateway': WhatsappMessageOrderPaymentGateway;
}

