/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Required when card action is url button. Only support `display_text` and `url`. Button display text Max 20 chars.
 * @export
 * @interface WhatsappMessageInteractiveActionCardActionParameters
 */
export interface WhatsappMessageInteractiveActionCardActionParameters {
    /**
     * Text of the CTA URL button. Maximum length: 20 bytes.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionCardActionParameters
     */
    'display_text'?: string;
    /**
     * URL of the CTA URL button.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionCardActionParameters
     */
    'url'?: string;
}

