/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageMedia } from './whatsapp-message-media';

/**
 *
 * @export
 * @interface WhatsappMessageInteractiveActionCardHeader
 */
export interface WhatsappMessageInteractiveActionCardHeader {
    /**
     * **Required.** The header type you would like to use. - `video`: Used for Reply Buttons. - `image`: Used for Reply Buttons.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionCardHeader
     */
    'type'?: WhatsappMessageInteractiveActionCardHeaderTypeEnum;
    /**
     *
     * @type {WhatsappMessageMedia}
     * @memberof WhatsappMessageInteractiveActionCardHeader
     */
    'image'?: WhatsappMessageMedia;
    /**
     *
     * @type {WhatsappMessageMedia}
     * @memberof WhatsappMessageInteractiveActionCardHeader
     */
    'video'?: WhatsappMessageMedia;
}

export const WhatsappMessageInteractiveActionCardHeaderTypeEnum = {
    Image: 'image',
    Video: 'video'
} as const;

export type WhatsappMessageInteractiveActionCardHeaderTypeEnum = typeof WhatsappMessageInteractiveActionCardHeaderTypeEnum[keyof typeof WhatsappMessageInteractiveActionCardHeaderTypeEnum];


