/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Page } from './page';
import { WhatsappPhoneNumber } from './whatsapp-phone-number';

/**
 * Represents a given page of WhatsApp phone numbers.
 * @export
 * @interface WhatsappPhoneNumberPage
 */
export interface WhatsappPhoneNumberPage {
    /**
     * An array containing WhatsApp phone number objects.
     * @type {Array<WhatsappPhoneNumber>}
     * @memberof WhatsappPhoneNumberPage
     */
    'items'?: Array<WhatsappPhoneNumber>;
    /**
     * The position of the item this page starts from, zero-based. e.g., the 11th item is at offset 10.
     * @type {number}
     * @memberof WhatsappPhoneNumberPage
     */
    'offset': number;
    /**
     * A limit on the number of items to be returned, between 1 and 100, defaults to 10.
     * @type {number}
     * @memberof WhatsappPhoneNumberPage
     */
    'limit': number;
    /**
     * The actual number of items in the page.
     * @type {number}
     * @memberof WhatsappPhoneNumberPage
     */
    'length': number;
    /**
     * The total number of items. This field is returned only when the request parameter `includeTotal` is set to `true`.
     * @type {number}
     * @memberof WhatsappPhoneNumberPage
     */
    'total'?: number;
}

