/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Industry of the WhatsApp phone number business profile. This can be either an empty string or one of the accepted values.
 * @export
 * @enum {string}
 */

export const WhatsappPhoneNumberProfileVertical = {
    Other: 'OTHER',
    Auto: 'AUTO',
    Beauty: 'BEAUTY',
    Apparel: 'APPAREL',
    Edu: 'EDU',
    Entertain: 'ENTERTAIN',
    EventPlan: 'EVENT_PLAN',
    Finance: 'FINANCE',
    Grocery: 'GROCERY',
    Govt: 'GOVT',
    Hotel: 'HOTEL',
    Health: 'HEALTH',
    Nonprofit: 'NONPROFIT',
    ProfServices: 'PROF_SERVICES',
    Retail: 'RETAIL',
    Travel: 'TRAVEL',
    Restaurant: 'RESTAURANT'
} as const;

export type WhatsappPhoneNumberProfileVertical = typeof WhatsappPhoneNumberProfileVertical[keyof typeof WhatsappPhoneNumberProfileVertical];



