/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * When the message type is set to `system`, this field is included. This object is added to Webhooks if a user has changed their phone number and if a user\'s identity has potentially changed on WhatsApp.
 * @export
 * @interface WhatsappInboundMessageSystem
 */
export interface WhatsappInboundMessageSystem {
    /**
     * Describes the system message event. Supported use cases are: - Phone number update: for when a user changes from an old number to a new number. - Identity update: for when a user identity has changed.
     * @type {string}
     * @memberof WhatsappInboundMessageSystem
     */
    'body'?: string;
    /**
     * **Added to Webhooks for phone number updates.**  New WhatsApp ID of the customer.
     * @type {string}
     * @memberof WhatsappInboundMessageSystem
     */
    'new_wa_id'?: string;
    /**
     * Supported types are: - `user_changed_number`: for a user changed number notification. - `user_identity_changed`: for user identity changed notification.
     * @type {string}
     * @memberof WhatsappInboundMessageSystem
     */
    'type'?: string;
    /**
     * **Added to Webhooks for identity updates.**  The new WhatsApp user ID of the customer.
     * @type {string}
     * @memberof WhatsappInboundMessageSystem
     */
    'user'?: string;
}

