/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Sent when a customer responds to a call permission request. Returned when `type` is `call_permission_reply`. This occurs when WhatsApp prompts users to grant callback permissions after they call your business.
 * @export
 * @interface WhatsappInboundMessageInteractiveCallPermissionReply
 */
export interface WhatsappInboundMessageInteractiveCallPermissionReply {
    /**
     * The customer\'s response to the call permission request. - `accept`: User granted permission for business to call back - `reject`: User rejected permission for business to call back
     * @type {string}
     * @memberof WhatsappInboundMessageInteractiveCallPermissionReply
     */
    'response'?: WhatsappInboundMessageInteractiveCallPermissionReplyResponseEnum;
    /**
     * The timestamp (in seconds) when the call permission expires. Only present when response is \"accept\" and is_permanent is false.
     * @type {number}
     * @memberof WhatsappInboundMessageInteractiveCallPermissionReply
     */
    'expiration_timestamp'?: number;
    /**
     * Whether the permission is permanent or temporary. - `true`: Permanent authorization (no expiration) - `false`: Temporary authorization (expires at expiration_timestamp)
     * @type {boolean}
     * @memberof WhatsappInboundMessageInteractiveCallPermissionReply
     */
    'is_permanent'?: boolean;
    /**
     * The source of this permission response. - `user_action`: User explicitly approved or rejected the permission - `automatic`: Automatic permission approval due to the WhatsApp user initiating the call
     * @type {string}
     * @memberof WhatsappInboundMessageInteractiveCallPermissionReply
     */
    'response_source'?: WhatsappInboundMessageInteractiveCallPermissionReplyResponseSourceEnum;
}

export const WhatsappInboundMessageInteractiveCallPermissionReplyResponseEnum = {
    Accept: 'accept',
    Reject: 'reject'
} as const;

export type WhatsappInboundMessageInteractiveCallPermissionReplyResponseEnum = typeof WhatsappInboundMessageInteractiveCallPermissionReplyResponseEnum[keyof typeof WhatsappInboundMessageInteractiveCallPermissionReplyResponseEnum];
export const WhatsappInboundMessageInteractiveCallPermissionReplyResponseSourceEnum = {
    UserAction: 'user_action',
    Automatic: 'automatic'
} as const;

export type WhatsappInboundMessageInteractiveCallPermissionReplyResponseSourceEnum = typeof WhatsappInboundMessageInteractiveCallPermissionReplyResponseSourceEnum[keyof typeof WhatsappInboundMessageInteractiveCallPermissionReplyResponseSourceEnum];


