/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Category of WhatsApp templates. `TRANSACTIONAL`: Send account updates, order updates, alerts, and more to share important information. `MARKETING`: Send promotional offers, product announcements, and more to increase awareness and engagement. `OTP`: Send codes that allow your customers to access their accounts.
 * @export
 * @enum {string}
 */

export const WhatsappTemplateCategory = {
    /**
    * Send account updates, order updates, alerts, and more to share important information.
    */
    Transactional: 'TRANSACTIONAL',
    /**
    * Send promotional offers, product announcements, and more to increase awareness and engagement.
    */
    Marketing: 'MARKETING',
    /**
    * Send codes that allow your customers to access their accounts.
    */
    Otp: 'OTP'
} as const;

export type WhatsappTemplateCategory = typeof WhatsappTemplateCategory[keyof typeof WhatsappTemplateCategory];



