/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Indicates button OTP type. Set to `COPY_CODE` if you want the template to use a copy code button, or `ONE_TAP` to have it use a one-tap autofill button.
 * @export
 * @enum {string}
 */

export const WhatsappTemplateComponentButtonOtpType = {
    CopyCode: 'COPY_CODE',
    OneTap: 'ONE_TAP'
} as const;

export type WhatsappTemplateComponentButtonOtpType = typeof WhatsappTemplateComponentButtonOtpType[keyof typeof WhatsappTemplateComponentButtonOtpType];



