/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageInteractiveAction } from './whatsapp-message-interactive-action';
import { WhatsappMessageInteractiveBody } from './whatsapp-message-interactive-body';
import { WhatsappMessageInteractiveFooter } from './whatsapp-message-interactive-footer';
import { WhatsappMessageInteractiveHeader } from './whatsapp-message-interactive-header';

/**
 * Use for `interactive` messages. See also [WhatsApp Interactive Object](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#interactive-object).
 * @export
 * @interface WhatsappMessageInteractive
 */
export interface WhatsappMessageInteractive {
    /**
     * The type of interactive message you want to send. - `button`: Use for Reply Buttons. - `list`: Use for List Messages. - `cta_url`: Use for Call-To-Action (CTA) URL Button Messages. - `product`: Use for Single Product Messages. - `product_list`: Use for Multi-Product Messages.
     * @type {string}
     * @memberof WhatsappMessageInteractive
     */
    'type': WhatsappMessageInteractiveTypeEnum;
    /**
     * 
     * @type {WhatsappMessageInteractiveAction}
     * @memberof WhatsappMessageInteractive
     */
    'action': WhatsappMessageInteractiveAction;
    /**
     * 
     * @type {WhatsappMessageInteractiveBody}
     * @memberof WhatsappMessageInteractive
     */
    'body'?: WhatsappMessageInteractiveBody;
    /**
     * 
     * @type {WhatsappMessageInteractiveHeader}
     * @memberof WhatsappMessageInteractive
     */
    'header'?: WhatsappMessageInteractiveHeader;
    /**
     * 
     * @type {WhatsappMessageInteractiveFooter}
     * @memberof WhatsappMessageInteractive
     */
    'footer'?: WhatsappMessageInteractiveFooter;
}

export const WhatsappMessageInteractiveTypeEnum = {
    /**
    * Use for Reply Buttons.
    */
    Button: 'button',
    /**
    * Use for List Messages.
    */
    List: 'list',
    /**
    * Use for Call-To-Action (CTA) URL Button Messages.
    */
    CtaUrl: 'cta_url',
    /**
    * Use for Single Product Messages.
    */
    Product: 'product',
    /**
    * Use for Multi-Product Messages.
    */
    ProductList: 'product_list'
} as const;

export type WhatsappMessageInteractiveTypeEnum = typeof WhatsappMessageInteractiveTypeEnum[keyof typeof WhatsappMessageInteractiveTypeEnum];


