/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MetaBusinessAccountVerificationStatus } from './meta-business-account-verification-status';
import { WhatsappAuthIntlRateEligibilityCountry } from './whatsapp-auth-intl-rate-eligibility-country';
import { WhatsappBusinessAccountBanState } from './whatsapp-business-account-ban-state';
import { WhatsappBusinessAccountRestrictionInfo } from './whatsapp-business-account-restriction-info';
import { WhatsappBusinessAccountReviewStatus } from './whatsapp-business-account-review-status';
import { WhatsappBusinessAccountUpdateEventEnum } from './whatsapp-business-account-update-event-enum';
import { WhatsappReviewDecision } from './whatsapp-review-decision';

/**
 * Represents a specific [WhatsApp Business Account (WABA)](https://developers.facebook.com/docs/whatsapp/overview/business-accounts).
 * @export
 * @interface WhatsappBusinessAccount
 */
export interface WhatsappBusinessAccount {
    /**
     * WhatApp Business Account ID.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'id'?: string;
    /**
     * User-friendly name to differentiate WhatsApp Business Accounts.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'name'?: string;
    /**
     * The currency in which the payment transactions for the WhatsApp Business Account will be processed.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'currency'?: string;
    /**
     * Namespace string for the message templates that belong to the WhatsApp Business Account.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'messageTemplateNamespace'?: string;
    /**
     * 
     * @type {WhatsappBusinessAccountReviewStatus}
     * @memberof WhatsappBusinessAccount
     */
    'accountReviewStatus'?: WhatsappBusinessAccountReviewStatus;
    /**
     * Business Portfolio ID.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'businessId'?: string;
    /**
     * Business Portfolio Name.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'businessName'?: string;
    /**
     * Business Portfolio Status,Default:APPROVED
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'businessStatus'?: string;
    /**
     * 
     * @type {MetaBusinessAccountVerificationStatus}
     * @memberof WhatsappBusinessAccount
     */
    'businessVerificationStatus'?: MetaBusinessAccountVerificationStatus;
    /**
     * Country of the WhatsApp Business Account\'s owning Meta Business account.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'country'?: string;
    /**
     * Ownership type of the WhatsApp Business Account.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'ownershipType'?: string;
    /**
     * Whether we have attached a payment method to the WhatsApp Business Account.
     * @type {boolean}
     * @memberof WhatsappBusinessAccount
     */
    'paymentMethodAttached'?: boolean;
    /**
     * Primary funding ID for the WhatsApp Business Account paid service.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'primaryFundingId'?: string;
    /**
     * The purchase order number supplied by the business for payment management purposes.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'purchaseOrderNumber'?: string;
    /**
     * The timezone ID of the WhatsApp Business Account. See [Timezone IDs](https://developers.facebook.com/docs/marketing-api/reference/ad-account/timezone-ids).
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'timezoneId'?: string;
    /**
     * 
     * @type {WhatsappReviewDecision}
     * @memberof WhatsappBusinessAccount
     */
    'decision'?: WhatsappReviewDecision;
    /**
     * 
     * @type {WhatsappBusinessAccountUpdateEventEnum}
     * @memberof WhatsappBusinessAccount
     */
    'updateEvent'?: WhatsappBusinessAccountUpdateEventEnum;
    /**
     * 
     * @type {WhatsappBusinessAccountBanState}
     * @memberof WhatsappBusinessAccount
     */
    'banState'?: WhatsappBusinessAccountBanState;
    /**
     * The date when the WABA is banned.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'banDate'?: string;
    /**
     * Used to report violations imposed on the WABA. See also [WhatsApp Business Platform Policy Violations](https://developers.facebook.com/docs/whatsapp/overview/policy-enforcement/violations).
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'violationType'?: string;
    /**
     * Used to report restrictions imposed on the WABA, when that WABA violates [WhatsApp Business Platform policies](https://developers.facebook.com/docs/whatsapp/overview/policy-enforcement).
     * @type {Array<WhatsappBusinessAccountRestrictionInfo>}
     * @memberof WhatsappBusinessAccount
     */
    'restrictions'?: Array<WhatsappBusinessAccountRestrictionInfo>;
    /**
     * Starting June 1, 2024, we are updating our authentication rate card and introducing a new authentication-international rate. This rate will apply in the the following countries: - June 1, 2024 – Indonesia (country calling code +62, country code `ID`) - July 1, 2024 – India (country calling code +91, country code `IN`)  See also [Authentication-International Rates](https://developers.facebook.com/docs/whatsapp/pricing/authentication-international-rates).
     * @type {Array<WhatsappAuthIntlRateEligibilityCountry>}
     * @memberof WhatsappBusinessAccount
     */
    'authIntlRateEligibilityCountries'?: Array<WhatsappAuthIntlRateEligibilityCountry>;
    /**
     * Your primary business location is the country where your business is based. It will appear in the Business Manager under the Primary Business Location field starting May 1, 2024. [ISO 3166-1 alpha-2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'primaryBusinessLocation'?: string;
    /**
     * The owning business portfolio\'s messaging limit. Starting October 7, 2025, messaging limits will instead be calculated and set on a business portfolio basis, and will be shared by all business phone numbers within each portfolio. See also [phone_number_quality_update webhook reference](https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks/reference/phone_number_quality_update). - `TIER_NOT_SET`: The business phone number has not been used to send a message yet. - `TIER_50`: Messaging limit of 50 business-initiated conversations in a rolling 24-hour period. - `TIER_250`: Messaging limit of 250 business-initiated conversations in a rolling 24-hour period. - `TIER_2K`: Messaging limit of 2,000 business-initiated conversations in a rolling 24-hour period. - `TIER_10K`: Messaging limit of 10,000 business-initiated conversations in a rolling 24-hour period. - `TIER_100K`: Messaging limit of 100,000 business-initiated conversations in a rolling 24-hour period. - `TIER_UNLIMITED`: The business phone number has higher throughput with unlimited business-initiated conversations.
     * @type {string}
     * @memberof WhatsappBusinessAccount
     */
    'whatsappBusinessManagerMessagingLimit'?: string;
}

