/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WhatsappCallingPreAcceptRequest
 */
export interface WhatsappCallingPreAcceptRequest {
    /**
     * The WhatsApp Business phone number ID.
     * @type {string}
     * @memberof WhatsappCallingPreAcceptRequest
     */
    'phoneId': string;
    /**
     * The WhatsApp call ID. Required for inbound call operations. This ID is received from the Call Connect webhook when a WhatsApp user initiates the call.
     * @type {string}
     * @memberof WhatsappCallingPreAcceptRequest
     */
    'wacid': string;
    /**
     * The SDP type for pre-accept operations. Must be \"answer\".
     * @type {string}
     * @memberof WhatsappCallingPreAcceptRequest
     */
    'sdpType': WhatsappCallingPreAcceptRequestSdpTypeEnum;
    /**
     * The Session Description Protocol (SDP) information compliant with [RFC 8866](https://datatracker.ietf.org/doc/html/rfc8866). Contains media session parameters for the WebRTC connection.
     * @type {string}
     * @memberof WhatsappCallingPreAcceptRequest
     */
    'sdp': string;
}

export const WhatsappCallingPreAcceptRequestSdpTypeEnum = {
    Answer: 'answer'
} as const;

export type WhatsappCallingPreAcceptRequestSdpTypeEnum = typeof WhatsappCallingPreAcceptRequestSdpTypeEnum[keyof typeof WhatsappCallingPreAcceptRequestSdpTypeEnum];


