/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappGroupWebhookConversation } from './whatsapp-group-webhook-conversation';
import { WhatsappGroupWebhookPricing } from './whatsapp-group-webhook-pricing';

/**
 * Group message status detail.
 * @export
 * @interface WhatsappGroupWebhookMessageStatus
 */
export interface WhatsappGroupWebhookMessageStatus {
    /**
     * WhatsApp message ID.
     * @type {string}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'id'?: string;
    /**
     * Message status.
     * @type {string}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'status'?: string;
    /**
     * Unix timestamp indicating when the message status was updated.
     * @type {number}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'timestamp'?: number;
    /**
     * Recipient group ID.
     * @type {string}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'recipientId'?: string;
    /**
     * Recipient type.
     * @type {string}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'recipientType'?: WhatsappGroupWebhookMessageStatusRecipientTypeEnum;
    /**
     * WhatsApp user ID of the recipient participant.
     * @type {string}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'recipientParticipantId'?: string;
    /**
     * Business-scoped user ID of the recipient participant.
     * @type {string}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'recipientUserId'?: string;
    /**
     * Parent business-scoped user ID of the recipient participant.
     * @type {string}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'parentRecipientUserId'?: string;
    /**
     * 
     * @type {WhatsappGroupWebhookConversation}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'conversation'?: WhatsappGroupWebhookConversation;
    /**
     * 
     * @type {WhatsappGroupWebhookPricing}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'pricing'?: WhatsappGroupWebhookPricing;
    /**
     * Errors returned by WhatsApp.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof WhatsappGroupWebhookMessageStatus
     */
    'errors'?: Array<{ [key: string]: any; }>;
}

export const WhatsappGroupWebhookMessageStatusRecipientTypeEnum = {
    Group: 'group'
} as const;

export type WhatsappGroupWebhookMessageStatusRecipientTypeEnum = typeof WhatsappGroupWebhookMessageStatusRecipientTypeEnum[keyof typeof WhatsappGroupWebhookMessageStatusRecipientTypeEnum];


