/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk } from './whatsapp-message-order-payment-setting-payment-gateway-billdesk';
import { WhatsappMessageOrderPaymentSettingPaymentGatewayPayu } from './whatsapp-message-order-payment-setting-payment-gateway-payu';
import { WhatsappMessageOrderPaymentSettingPaymentGatewayRazorpay } from './whatsapp-message-order-payment-setting-payment-gateway-razorpay';
import { WhatsappMessageOrderPaymentSettingPaymentGatewayZaakpay } from './whatsapp-message-order-payment-setting-payment-gateway-zaakpay';

/**
 * An object that describes payment account information.
 * @export
 * @interface WhatsappMessageOrderPaymentGateway
 */
export interface WhatsappMessageOrderPaymentGateway {
    /**
     * Payment type. Must set this to `billdesk`, `razorpay`, `payu`, or `zaakpay`, if you have linked your BillDesk, Razorpay, PayU, or Zaakpay payment gateway to accept payments.
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentGateway
     */
    'type': WhatsappMessageOrderPaymentGatewayTypeEnum;
    /**
     * The name of the pre-configured payment configuration to use for this order and must not exceed 60 characters. This value must match with a payment configuration set up on the WhatsApp Business Manager.
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentGateway
     */
    'configuration_name': string;
    /**
     * 
     * @type {WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk}
     * @memberof WhatsappMessageOrderPaymentGateway
     */
    'billdesk'?: WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk;
    /**
     * 
     * @type {WhatsappMessageOrderPaymentSettingPaymentGatewayPayu}
     * @memberof WhatsappMessageOrderPaymentGateway
     */
    'payu'?: WhatsappMessageOrderPaymentSettingPaymentGatewayPayu;
    /**
     * 
     * @type {WhatsappMessageOrderPaymentSettingPaymentGatewayRazorpay}
     * @memberof WhatsappMessageOrderPaymentGateway
     */
    'razorpay'?: WhatsappMessageOrderPaymentSettingPaymentGatewayRazorpay;
    /**
     * 
     * @type {WhatsappMessageOrderPaymentSettingPaymentGatewayZaakpay}
     * @memberof WhatsappMessageOrderPaymentGateway
     */
    'zaakpay'?: WhatsappMessageOrderPaymentSettingPaymentGatewayZaakpay;
}

export const WhatsappMessageOrderPaymentGatewayTypeEnum = {
    Billdesk: 'billdesk',
    Razorpay: 'razorpay',
    Payu: 'payu',
    Zaakpay: 'zaakpay'
} as const;

export type WhatsappMessageOrderPaymentGatewayTypeEnum = typeof WhatsappMessageOrderPaymentGatewayTypeEnum[keyof typeof WhatsappMessageOrderPaymentGatewayTypeEnum];


