/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappGroupCustomerProfile } from './whatsapp-group-customer-profile';
import { WhatsappGroupJoinApprovalMode } from './whatsapp-group-join-approval-mode';
import { WhatsappGroupWebhookField } from './whatsapp-group-webhook-field';
import { WhatsappGroupWebhookMessageStatus } from './whatsapp-group-webhook-message-status';
import { WhatsappGroupWebhookParticipant } from './whatsapp-group-webhook-participant';
import { WhatsappGroupWebhookSetting } from './whatsapp-group-webhook-setting';
import { WhatsappGroupWebhookStatus } from './whatsapp-group-webhook-status';
import { WhatsappGroupWebhookStatusContact } from './whatsapp-group-webhook-status-contact';
import { WhatsappGroupWebhookType } from './whatsapp-group-webhook-type';

/**
 * WhatsApp group webhook payload.
 * @export
 * @interface WhatsappGroupWebhook
 */
export interface WhatsappGroupWebhook {
    /**
     * WhatsApp Business Account ID.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'wabaId'?: string;
    /**
     * The display phone number from WhatsApp webhook metadata.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'displayPhoneNumber'?: string;
    /**
     * WhatsApp phone number ID.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'phoneNumberId'?: string;
    /**
     * 
     * @type {WhatsappGroupWebhookField}
     * @memberof WhatsappGroupWebhook
     */
    'field'?: WhatsappGroupWebhookField;
    /**
     * 
     * @type {WhatsappGroupWebhookType}
     * @memberof WhatsappGroupWebhook
     */
    'type'?: WhatsappGroupWebhookType;
    /**
     * The request ID returned by an asynchronous group API operation.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'requestId'?: string;
    /**
     * 
     * @type {WhatsappGroupWebhookStatus}
     * @memberof WhatsappGroupWebhook
     */
    'status'?: WhatsappGroupWebhookStatus;
    /**
     * WhatsApp group ID.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'groupId'?: string;
    /**
     * The group invite link.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'inviteLink'?: string;
    /**
     * The reason for a participant, join request, or removal event.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'reason'?: string;
    /**
     * Indicates who initiated a participant removal event.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'initiatedBy'?: WhatsappGroupWebhookInitiatedByEnum;
    /**
     * The join request ID.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'joinRequestId'?: string;
    /**
     * WhatsApp user ID for a single participant event.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'waId'?: string;
    /**
     * Business-scoped user ID for a single participant event.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'recipientUserId'?: string;
    /**
     * Parent business-scoped user ID for a single participant event.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'parentRecipientUserId'?: string;
    /**
     * 
     * @type {WhatsappGroupCustomerProfile}
     * @memberof WhatsappGroupWebhook
     */
    'customerProfile'?: WhatsappGroupCustomerProfile;
    /**
     * The group subject.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'subject'?: string;
    /**
     * The group description.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'description'?: string;
    /**
     * 
     * @type {WhatsappGroupJoinApprovalMode}
     * @memberof WhatsappGroupWebhook
     */
    'joinApprovalMode'?: WhatsappGroupJoinApprovalMode;
    /**
     * Participants added to the group.
     * @type {Array<WhatsappGroupWebhookParticipant>}
     * @memberof WhatsappGroupWebhook
     */
    'addedParticipants'?: Array<WhatsappGroupWebhookParticipant>;
    /**
     * Participants removed from the group.
     * @type {Array<WhatsappGroupWebhookParticipant>}
     * @memberof WhatsappGroupWebhook
     */
    'removedParticipants'?: Array<WhatsappGroupWebhookParticipant>;
    /**
     * Participants that failed to be added or removed.
     * @type {Array<WhatsappGroupWebhookParticipant>}
     * @memberof WhatsappGroupWebhook
     */
    'failedParticipants'?: Array<WhatsappGroupWebhookParticipant>;
    /**
     * Group setting update details.
     * @type {Array<WhatsappGroupWebhookSetting>}
     * @memberof WhatsappGroupWebhook
     */
    'settings'?: Array<WhatsappGroupWebhookSetting>;
    /**
     * Errors returned by WhatsApp.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof WhatsappGroupWebhook
     */
    'errors'?: Array<{ [key: string]: any; }>;
    /**
     * Contacts included in group message status webhooks.
     * @type {Array<WhatsappGroupWebhookStatusContact>}
     * @memberof WhatsappGroupWebhook
     */
    'contacts'?: Array<WhatsappGroupWebhookStatusContact>;
    /**
     * Group message status details.
     * @type {Array<WhatsappGroupWebhookMessageStatus>}
     * @memberof WhatsappGroupWebhook
     */
    'statuses'?: Array<WhatsappGroupWebhookMessageStatus>;
    /**
     * The time at which WhatsApp triggered this webhook.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'webhookTime'?: string;
    /**
     * Idempotency key for deduplicating group webhook events.
     * @type {string}
     * @memberof WhatsappGroupWebhook
     */
    'dedupeKey'?: string;
}

export const WhatsappGroupWebhookInitiatedByEnum = {
    Business: 'business',
    Participant: 'participant'
} as const;

export type WhatsappGroupWebhookInitiatedByEnum = typeof WhatsappGroupWebhookInitiatedByEnum[keyof typeof WhatsappGroupWebhookInitiatedByEnum];


