/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WhatsappCallingTerminateRequest
 */
export interface WhatsappCallingTerminateRequest {
    /**
     * The WhatsApp Business phone number ID.
     * @type {string}
     * @memberof WhatsappCallingTerminateRequest
     */
    'phoneId': string;
    /**
     * The WhatsApp call ID. Required for terminate operations. This ID is received from the Call Connect webhook when a WhatsApp user initiates the call.
     * @type {string}
     * @memberof WhatsappCallingTerminateRequest
     */
    'wacid': string;
}

