/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WhatsappMessageInteractiveActionButtonsInnerReply
 */
export interface WhatsappMessageInteractiveActionButtonsInnerReply {
    /**
     * Button title. It cannot be an empty string and must be unique within the message. Emojis are supported, markdown is not.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionButtonsInnerReply
     */
    'title'?: string;
    /**
     * Unique identifier for your button. This ID is returned in the webhook when the button is clicked by the user.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionButtonsInnerReply
     */
    'id'?: string;
}

