/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Pricing information included in group message status webhooks.
 * @export
 * @interface WhatsappGroupWebhookPricing
 */
export interface WhatsappGroupWebhookPricing {
    /**
     * Whether the message is billable.
     * @type {boolean}
     * @memberof WhatsappGroupWebhookPricing
     */
    'billable'?: boolean;
    /**
     * Pricing model.
     * @type {string}
     * @memberof WhatsappGroupWebhookPricing
     */
    'pricingModel'?: string;
    /**
     * Pricing type.
     * @type {string}
     * @memberof WhatsappGroupWebhookPricing
     */
    'type'?: string;
    /**
     * Pricing category.
     * @type {string}
     * @memberof WhatsappGroupWebhookPricing
     */
    'category'?: string;
}

