/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WhatsappCallingRequest
 */
export interface WhatsappCallingRequest {
    /**
     * The WhatsApp Business phone number ID.
     * @type {string}
     * @memberof WhatsappCallingRequest
     */
    'phoneId'?: string;
    /**
     * The caller\'s phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format. Required for connect operations when phoneId is empty.
     * @type {string}
     * @memberof WhatsappCallingRequest
     */
    'from'?: string;
    /**
     * The callee\'s phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format. Required for outbound call connections.
     * @type {string}
     * @memberof WhatsappCallingRequest
     */
    'to'?: string;
    /**
     * The WhatsApp call ID. Required for inbound call operations. This ID is received from the Call Connect webhook when a WhatsApp user initiates the call.
     * @type {string}
     * @memberof WhatsappCallingRequest
     */
    'wacid'?: string;
    /**
     * The SDP type. For pre-accept and accept operations, must be \"answer\".
     * @type {string}
     * @memberof WhatsappCallingRequest
     */
    'sdpType'?: WhatsappCallingRequestSdpTypeEnum;
    /**
     * The Session Description Protocol (SDP) information compliant with [RFC 8866](https://datatracker.ietf.org/doc/html/rfc8866). Required for pre-accept and accept operations. Contains media session parameters for the WebRTC connection.
     * @type {string}
     * @memberof WhatsappCallingRequest
     */
    'sdp'?: string;
}

export const WhatsappCallingRequestSdpTypeEnum = {
    Offer: 'offer',
    Answer: 'answer'
} as const;

export type WhatsappCallingRequestSdpTypeEnum = typeof WhatsappCallingRequestSdpTypeEnum[keyof typeof WhatsappCallingRequestSdpTypeEnum];


