/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappPhoneNumberNameStatus } from './whatsapp-phone-number-name-status';

/**
 * WhatsApp Phone Number Display Name Modify Result
 * @export
 * @interface WhatsappPhoneNameUpdateResponse
 */
export interface WhatsappPhoneNameUpdateResponse {
    /**
     * The verified name
     * @type {string}
     * @memberof WhatsappPhoneNameUpdateResponse
     */
    'verifiedName'?: string;
    /**
     * 
     * @type {WhatsappPhoneNumberNameStatus}
     * @memberof WhatsappPhoneNameUpdateResponse
     */
    'nameStatus'?: WhatsappPhoneNumberNameStatus;
    /**
     * The new name you want to modify
     * @type {string}
     * @memberof WhatsappPhoneNameUpdateResponse
     */
    'newName'?: string;
    /**
     * 
     * @type {WhatsappPhoneNumberNameStatus}
     * @memberof WhatsappPhoneNameUpdateResponse
     */
    'newNameStatus'?: WhatsappPhoneNumberNameStatus;
}

