/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageMedia } from './whatsapp-message-media';
import { WhatsappMessageTemplateComponentParameterLimitedTimeOffer } from './whatsapp-message-template-component-parameter-limited-time-offer';

/**
 * See [Parameter Object](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#parameter-object), [Button Parameter Object](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#button-parameter-object.
 * @export
 * @interface WhatsappMessageTemplateComponentParameter
 */
export interface WhatsappMessageTemplateComponentParameter {
    /**
     * **Required.** Describes the parameter type. - `text`: Used when the template component type is `BODY`, or the `HEADER` component format is `TEXT`. - `image`: Used when the template `HEADER` component is `IMAGE`. - `video`: Used when the template `HEADER` component is `VIDEO`. - `document`: Used when the template `HEADER` component is `DOCUMENT`. - `payload`: Used when the template component button type is `QUICK_REPLY`. - `coupon_code`: Used when the template component button type is `COPY_CODE`. - `limited_time_offer`: Used when the template component type is `LIMITED_TIME_OFFER`.
     * @type {string}
     * @memberof WhatsappMessageTemplateComponentParameter
     */
    'type'?: WhatsappMessageTemplateComponentParameterTypeEnum;
    /**
     * **Required when `type` = `text`.** The message\'s text. For the header component, the character limit is 60 characters. For the body component, the character limit is 1024 characters. For url buttons, it indicates the developer-provided suffix that is appended to the predefined prefix URL in the template.
     * @type {string}
     * @memberof WhatsappMessageTemplateComponentParameter
     */
    'text'?: string;
    /**
     * Required for `quick_reply` buttons. Developer-defined payload that is returned when the button is clicked in addition to the display text on the button.
     * @type {string}
     * @memberof WhatsappMessageTemplateComponentParameter
     */
    'payload'?: string;
    /**
     * **Required when `type` = `coupon_code`.** The coupon code to be copied when the customer taps the button.
     * @type {string}
     * @memberof WhatsappMessageTemplateComponentParameter
     */
    'coupon_code'?: string;
    /**
     * 
     * @type {WhatsappMessageMedia}
     * @memberof WhatsappMessageTemplateComponentParameter
     */
    'image'?: WhatsappMessageMedia;
    /**
     * 
     * @type {WhatsappMessageMedia}
     * @memberof WhatsappMessageTemplateComponentParameter
     */
    'video'?: WhatsappMessageMedia;
    /**
     * 
     * @type {WhatsappMessageMedia}
     * @memberof WhatsappMessageTemplateComponentParameter
     */
    'document'?: WhatsappMessageMedia;
    /**
     * 
     * @type {WhatsappMessageTemplateComponentParameterLimitedTimeOffer}
     * @memberof WhatsappMessageTemplateComponentParameter
     */
    'limited_time_offer'?: WhatsappMessageTemplateComponentParameterLimitedTimeOffer;
}

export const WhatsappMessageTemplateComponentParameterTypeEnum = {
    Text: 'text',
    Image: 'image',
    Video: 'video',
    Document: 'document',
    Payload: 'payload',
    CouponCode: 'coupon_code',
    LimitedTimeOffer: 'limited_time_offer'
} as const;

export type WhatsappMessageTemplateComponentParameterTypeEnum = typeof WhatsappMessageTemplateComponentParameterTypeEnum[keyof typeof WhatsappMessageTemplateComponentParameterTypeEnum];


