/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents the amount of an order.
 * @export
 * @interface WhatsappMessageOrderAmount
 */
export interface WhatsappMessageOrderAmount {
    /**
     * Must be `100` for `INR`.
     * @type {number}
     * @memberof WhatsappMessageOrderAmount
     */
    'offset': number;
    /**
     * Positive integer representing the amount value multiplied by offset.  For example, ₹12.34 has value 1234.
     * @type {number}
     * @memberof WhatsappMessageOrderAmount
     */
    'value': number;
    /**
     * Use only for `tax`, `shipping`, or `discount`. Description of the amount. Max character limit is 60 characters.
     * @type {string}
     * @memberof WhatsappMessageOrderAmount
     */
    'description'?: string;
    /**
     * Use only for `discount`. Text used for defining incentivised orders. If order is incentivised, the merchant needs to define this information. Max character limit is 60 characters.
     * @type {string}
     * @memberof WhatsappMessageOrderAmount
     */
    'discount_program_name'?: string;
}

