/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappGroupJoinApprovalMode } from './whatsapp-group-join-approval-mode';
import { WhatsappGroupParticipant } from './whatsapp-group-participant';

/**
 * WhatsApp group object.
 * @export
 * @interface WhatsappGroup
 */
export interface WhatsappGroup {
    /**
     * WhatsApp group ID.
     * @type {string}
     * @memberof WhatsappGroup
     */
    'groupId'?: string;
    /**
     * The group subject.
     * @type {string}
     * @memberof WhatsappGroup
     */
    'subject'?: string;
    /**
     * The group description.
     * @type {string}
     * @memberof WhatsappGroup
     */
    'description'?: string;
    /**
     * 
     * @type {WhatsappGroupJoinApprovalMode}
     * @memberof WhatsappGroup
     */
    'joinApprovalMode'?: WhatsappGroupJoinApprovalMode;
    /**
     * Whether the group is suspended.
     * @type {boolean}
     * @memberof WhatsappGroup
     */
    'suspended'?: boolean;
    /**
     * Unix timestamp indicating when the group was created.
     * @type {number}
     * @memberof WhatsappGroup
     */
    'creationTimestamp'?: number;
    /**
     * Total number of participants in the group.
     * @type {number}
     * @memberof WhatsappGroup
     */
    'totalParticipantCount'?: number;
    /**
     * Group participants.
     * @type {Array<WhatsappGroupParticipant>}
     * @memberof WhatsappGroup
     */
    'participants'?: Array<WhatsappGroupParticipant>;
}

