/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappFlowValidationErrorPointersInner } from './whatsapp-flow-validation-error-pointers-inner';

/**
 * Represents a validation error in a WhatsApp Flow.
 * @export
 * @interface WhatsappFlowValidationError
 */
export interface WhatsappFlowValidationError {
    /**
     * Error code.
     * @type {string}
     * @memberof WhatsappFlowValidationError
     */
    'error'?: string;
    /**
     * Error type.
     * @type {string}
     * @memberof WhatsappFlowValidationError
     */
    'errorType'?: string;
    /**
     * Error message.
     * @type {string}
     * @memberof WhatsappFlowValidationError
     */
    'message'?: string;
    /**
     * Start line of the error.
     * @type {number}
     * @memberof WhatsappFlowValidationError
     */
    'lineStart'?: number;
    /**
     * End line of the error.
     * @type {number}
     * @memberof WhatsappFlowValidationError
     */
    'lineEnd'?: number;
    /**
     * Start column of the error.
     * @type {number}
     * @memberof WhatsappFlowValidationError
     */
    'columnStart'?: number;
    /**
     * End column of the error.
     * @type {number}
     * @memberof WhatsappFlowValidationError
     */
    'columnEnd'?: number;
    /**
     * List of pointers to the error location.
     * @type {Array<WhatsappFlowValidationErrorPointersInner>}
     * @memberof WhatsappFlowValidationError
     */
    'pointers'?: Array<WhatsappFlowValidationErrorPointersInner>;
}

