/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappGroupWebhookConversationOrigin } from './whatsapp-group-webhook-conversation-origin';

/**
 * WhatsApp conversation object included in group message status webhooks.
 * @export
 * @interface WhatsappGroupWebhookConversation
 */
export interface WhatsappGroupWebhookConversation {
    /**
     * Conversation ID.
     * @type {string}
     * @memberof WhatsappGroupWebhookConversation
     */
    'id'?: string;
    /**
     * Unix timestamp indicating when the conversation expires.
     * @type {number}
     * @memberof WhatsappGroupWebhookConversation
     */
    'expirationTimestamp'?: number;
    /**
     * 
     * @type {WhatsappGroupWebhookConversationOrigin}
     * @memberof WhatsappGroupWebhookConversation
     */
    'origin'?: WhatsappGroupWebhookConversationOrigin;
}

