/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * When a user reacts to messages with an emoji, the message type is set to `reaction`, and this field is included.
 * @export
 * @interface WhatsappMessageReaction
 */
export interface WhatsappMessageReaction {
    /**
     * Specifies the `wamid` of the message received that contained the reaction.
     * @type {string}
     * @memberof WhatsappMessageReaction
     */
    'message_id': string;
    /**
     * **Required** when you send a `reaction` message. Set it to `\"\"` if you want to remove the emoji. **Optional** when you received a message from a user. This field is included when a user reacts to messages with an emoji. Otherwise, it indicates a user removed the emoji.
     * @type {string}
     * @memberof WhatsappMessageReaction
     */
    'emoji'?: string;
}

