/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappGroupCustomerProfile } from './whatsapp-group-customer-profile';

/**
 * Participant information included in group webhook payloads.
 * @export
 * @interface WhatsappGroupWebhookParticipant
 */
export interface WhatsappGroupWebhookParticipant {
    /**
     * The original participant input.
     * @type {string}
     * @memberof WhatsappGroupWebhookParticipant
     */
    'input'?: string;
    /**
     * WhatsApp user ID.
     * @type {string}
     * @memberof WhatsappGroupWebhookParticipant
     */
    'waId'?: string;
    /**
     * Business-scoped user ID.
     * @type {string}
     * @memberof WhatsappGroupWebhookParticipant
     */
    'recipientUserId'?: string;
    /**
     * Parent business-scoped user ID.
     * @type {string}
     * @memberof WhatsappGroupWebhookParticipant
     */
    'parentRecipientUserId'?: string;
    /**
     * 
     * @type {WhatsappGroupCustomerProfile}
     * @memberof WhatsappGroupWebhookParticipant
     */
    'customerProfile'?: WhatsappGroupCustomerProfile;
    /**
     * Errors returned by WhatsApp for this participant.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof WhatsappGroupWebhookParticipant
     */
    'errors'?: Array<{ [key: string]: any; }>;
}

