/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappTemplateComponentButton } from './whatsapp-template-component-button';
import { WhatsappTemplateComponentExample } from './whatsapp-template-component-example';

/**
 * 
 * @export
 * @interface WhatsappTemplateComponentCardComponent
 */
export interface WhatsappTemplateComponentCardComponent {
    /**
     * **Required.** Card component type. - `BODY`: Body components are text-only components. Cards can optionally include body text. - `HEADER`: Cards must have a media header (image or video). - `BUTTONS`: Buttons are optional interactive components that perform specific actions when tapped.
     * @type {string}
     * @memberof WhatsappTemplateComponentCardComponent
     */
    'type'?: WhatsappTemplateComponentCardComponentTypeEnum;
    /**
     * **Required for type `HEADER`.** Cards must have a media header (image or video).
     * @type {string}
     * @memberof WhatsappTemplateComponentCardComponent
     */
    'format'?: WhatsappTemplateComponentCardComponentFormatEnum;
    /**
     * Card body text supports variables. There is no maximum character limit on variables, but they count against the card body text limit of 160 characters.
     * @type {string}
     * @memberof WhatsappTemplateComponentCardComponent
     */
    'text'?: string;
    /**
     * **Required for type `BUTTONS`.** Cards can optionally include up to 2 quick reply buttons, phone number buttons, or URL buttons (button types can be mixed).
     * @type {Array<WhatsappTemplateComponentButton>}
     * @memberof WhatsappTemplateComponentCardComponent
     */
    'buttons'?: Array<WhatsappTemplateComponentButton>;
    /**
     * 
     * @type {WhatsappTemplateComponentExample}
     * @memberof WhatsappTemplateComponentCardComponent
     */
    'example'?: WhatsappTemplateComponentExample;
}

export const WhatsappTemplateComponentCardComponentTypeEnum = {
    Body: 'BODY',
    Header: 'HEADER',
    Buttons: 'BUTTONS'
} as const;

export type WhatsappTemplateComponentCardComponentTypeEnum = typeof WhatsappTemplateComponentCardComponentTypeEnum[keyof typeof WhatsappTemplateComponentCardComponentTypeEnum];
export const WhatsappTemplateComponentCardComponentFormatEnum = {
    Image: 'IMAGE',
    Video: 'VIDEO'
} as const;

export type WhatsappTemplateComponentCardComponentFormatEnum = typeof WhatsappTemplateComponentCardComponentFormatEnum[keyof typeof WhatsappTemplateComponentCardComponentFormatEnum];


