/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Calling feature settings for the phone number.
 * @export
 * @interface WhatsappPhoneNumberSettingsCalling
 */
export interface WhatsappPhoneNumberSettingsCalling {
    /**
     * Phone number ID.
     * @type {string}
     * @memberof WhatsappPhoneNumberSettingsCalling
     */
    'id'?: string;
    /**
     * Calling feature status: - `ENABLED`: Calling feature is enabled - `DISABLED`: Calling feature is disabled
     * @type {string}
     * @memberof WhatsappPhoneNumberSettingsCalling
     */
    'status'?: WhatsappPhoneNumberSettingsCallingStatusEnum;
    /**
     * Calling icon display configuration: - `DEFAULT`: Show icon by default - `DISABLE_ALL`: Hide all calling icons
     * @type {string}
     * @memberof WhatsappPhoneNumberSettingsCalling
     */
    'iconVisibility'?: WhatsappPhoneNumberSettingsCallingIconVisibilityEnum;
}

export const WhatsappPhoneNumberSettingsCallingStatusEnum = {
    Enabled: 'ENABLED',
    Disabled: 'DISABLED'
} as const;

export type WhatsappPhoneNumberSettingsCallingStatusEnum = typeof WhatsappPhoneNumberSettingsCallingStatusEnum[keyof typeof WhatsappPhoneNumberSettingsCallingStatusEnum];
export const WhatsappPhoneNumberSettingsCallingIconVisibilityEnum = {
    Default: 'DEFAULT',
    DisableAll: 'DISABLE_ALL'
} as const;

export type WhatsappPhoneNumberSettingsCallingIconVisibilityEnum = typeof WhatsappPhoneNumberSettingsCallingIconVisibilityEnum[keyof typeof WhatsappPhoneNumberSettingsCallingIconVisibilityEnum];


