/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageTemplateComponentParameter } from './whatsapp-message-template-component-parameter';

/**
 * Provide exactly one of `to` or `recipient`. If both are provided, `to` takes precedence and `recipient` is ignored.
 * @export
 * @interface WhatsappGroupInviteLinkMessageRequest
 */
export interface WhatsappGroupInviteLinkMessageRequest {
    /**
     * The recipient\'s phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format. Required when `recipient` is not provided.
     * @type {string}
     * @memberof WhatsappGroupInviteLinkMessageRequest
     */
    'to'?: string;
    /**
     * The recipient\'s WhatsApp Business-scoped user ID (BSUID) or parent BSUID. Required when `to` is not provided.
     * @type {string}
     * @memberof WhatsappGroupInviteLinkMessageRequest
     */
    'recipient'?: string;
    /**
     * The name of the approved WhatsApp template.
     * @type {string}
     * @memberof WhatsappGroupInviteLinkMessageRequest
     */
    'templateName': string;
    /**
     * The template language code.
     * @type {string}
     * @memberof WhatsappGroupInviteLinkMessageRequest
     */
    'languageCode': string;
    /**
     * Template body parameters in template variable order. Must include one group invite link parameter with `type=group_id` and `group_id=<groupId>`.
     * @type {Array<WhatsappMessageTemplateComponentParameter>}
     * @memberof WhatsappGroupInviteLinkMessageRequest
     */
    'parameters': Array<WhatsappMessageTemplateComponentParameter>;
}

