/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageTemplateComponent } from './whatsapp-message-template-component';

/**
 * Card component containing the parameters of the message.
 * @export
 * @interface WhatsappMessageTemplateComponentCard
 */
export interface WhatsappMessageTemplateComponentCard {
    /**
     * **Required.** Zero-indexed order in which card appears within the card carousel. 0 indicates first card, 1 indicates second card, etc.
     * @type {number}
     * @memberof WhatsappMessageTemplateComponentCard
     */
    'card_index'?: number;
    /**
     * Card component.
     * @type {Array<WhatsappMessageTemplateComponent>}
     * @memberof WhatsappMessageTemplateComponentCard
     */
    'components'?: Array<WhatsappMessageTemplateComponent>;
}

