/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageContactAddressesInner } from './whatsapp-message-contact-addresses-inner';
import { WhatsappMessageContactEmailsInner } from './whatsapp-message-contact-emails-inner';
import { WhatsappMessageContactName } from './whatsapp-message-contact-name';
import { WhatsappMessageContactOrg } from './whatsapp-message-contact-org';
import { WhatsappMessageContactPhonesInner } from './whatsapp-message-contact-phones-inner';
import { WhatsappMessageContactUrlsInner } from './whatsapp-message-contact-urls-inner';

/**
 * When the message type filed is set to `contacts`, this object is included in the message object. See also [WhatsApp message contacts object](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#contacts-object).
 * @export
 * @interface WhatsappMessageContact
 */
export interface WhatsappMessageContact {
    /**
     * 
     * @type {Array<WhatsappMessageContactAddressesInner>}
     * @memberof WhatsappMessageContact
     */
    'addresses'?: Array<WhatsappMessageContactAddressesInner>;
    /**
     * `YYYY-MM-DD` formatted string.
     * @type {string}
     * @memberof WhatsappMessageContact
     */
    'birthday'?: string;
    /**
     * 
     * @type {Array<WhatsappMessageContactEmailsInner>}
     * @memberof WhatsappMessageContact
     */
    'emails'?: Array<WhatsappMessageContactEmailsInner>;
    /**
     * 
     * @type {WhatsappMessageContactName}
     * @memberof WhatsappMessageContact
     */
    'name'?: WhatsappMessageContactName;
    /**
     * 
     * @type {WhatsappMessageContactOrg}
     * @memberof WhatsappMessageContact
     */
    'org'?: WhatsappMessageContactOrg;
    /**
     * Contact phone number(s) formatted as a phone object.
     * @type {Array<WhatsappMessageContactPhonesInner>}
     * @memberof WhatsappMessageContact
     */
    'phones'?: Array<WhatsappMessageContactPhonesInner>;
    /**
     * Contact URL(s) formatted as a urls object.
     * @type {Array<WhatsappMessageContactUrlsInner>}
     * @memberof WhatsappMessageContact
     */
    'urls'?: Array<WhatsappMessageContactUrlsInner>;
}

