/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappInboundMessageInteractiveButtonReply } from './whatsapp-inbound-message-interactive-button-reply';
import { WhatsappInboundMessageInteractiveCallPermissionReply } from './whatsapp-inbound-message-interactive-call-permission-reply';
import { WhatsappInboundMessageInteractiveListReply } from './whatsapp-inbound-message-interactive-list-reply';
import { WhatsappInboundMessageInteractiveNfmReply } from './whatsapp-inbound-message-interactive-nfm-reply';

/**
 * When a customer has interacted with your message, this object is included in the message object.
 * @export
 * @interface WhatsappInboundMessageInteractive
 */
export interface WhatsappInboundMessageInteractive {
    /**
     * The type of interactive message received. - `button_reply`: Sent when a customer clicks a button. - `list_reply`: Sent when a customer selects an item from a list. - `nfm_reply`: Sent when a customer responds to a WhatsApp Flow (Next Feature Messaging). - `call_permission_reply`: Sent when a customer responds to a call permission request.
     * @type {string}
     * @memberof WhatsappInboundMessageInteractive
     */
    'type'?: WhatsappInboundMessageInteractiveTypeEnum;
    /**
     * 
     * @type {WhatsappInboundMessageInteractiveButtonReply}
     * @memberof WhatsappInboundMessageInteractive
     */
    'button_reply'?: WhatsappInboundMessageInteractiveButtonReply;
    /**
     * 
     * @type {WhatsappInboundMessageInteractiveListReply}
     * @memberof WhatsappInboundMessageInteractive
     */
    'list_reply'?: WhatsappInboundMessageInteractiveListReply;
    /**
     * 
     * @type {WhatsappInboundMessageInteractiveNfmReply}
     * @memberof WhatsappInboundMessageInteractive
     */
    'nfm_reply'?: WhatsappInboundMessageInteractiveNfmReply;
    /**
     * 
     * @type {WhatsappInboundMessageInteractiveCallPermissionReply}
     * @memberof WhatsappInboundMessageInteractive
     */
    'call_permission_reply'?: WhatsappInboundMessageInteractiveCallPermissionReply;
}

export const WhatsappInboundMessageInteractiveTypeEnum = {
    ButtonReply: 'button_reply',
    ListReply: 'list_reply',
    NfmReply: 'nfm_reply',
    CallPermissionReply: 'call_permission_reply'
} as const;

export type WhatsappInboundMessageInteractiveTypeEnum = typeof WhatsappInboundMessageInteractiveTypeEnum[keyof typeof WhatsappInboundMessageInteractiveTypeEnum];


