/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappTemplateComponentButton } from './whatsapp-template-component-button';
import { WhatsappTemplateComponentCard } from './whatsapp-template-component-card';
import { WhatsappTemplateComponentExample } from './whatsapp-template-component-example';
import { WhatsappTemplateComponentLimitedTimeOffer } from './whatsapp-template-component-limited-time-offer';

/**
 * 
 * @export
 * @interface WhatsappTemplateComponent
 */
export interface WhatsappTemplateComponent {
    /**
     * **Required.** Template component type. - `BODY`: Body components are text-only components and are required by all templates. Templates are limited to one body component. - `HEADER`: Headers are optional components that appear at the top of template messages. Headers support text, media (images, videos, documents). Templates are limited to one header component. - `FOOTER`: Footers are optional text-only components that appear immediately after the body component. Templates are limited to one footer component. - `BUTTONS`: Buttons are optional interactive components that perform specific actions when tapped. - `LIMITED_TIME_OFFER`: Use for limited-time offer templates. The delivered message can display an offer expiration details section with a heading, an optional expiration timer, and the offer code itself. - `CAROUSEL`: Carousel templates allow you to send a single text message (1), accompanied by a set of up to 10 carousel cards (2) in a horizontally scrollable view.
     * @type {string}
     * @memberof WhatsappTemplateComponent
     */
    'type'?: WhatsappTemplateComponentTypeEnum;
    /**
     * **Required for type `HEADER`.**
     * @type {string}
     * @memberof WhatsappTemplateComponent
     */
    'format'?: WhatsappTemplateComponentFormatEnum;
    /**
     * For body text (type = `BODY`), maximum 1024 characters. For header text (type = `HEADER`, format = `TEXT`), maximum 60 characters. For footer text (type = `FOOTER`), maximum 60 characters. For card body text (`CAROUSEL` card component type = `BODY`), maximum 160 characters.
     * @type {string}
     * @memberof WhatsappTemplateComponent
     */
    'text'?: string;
    /**
     * **Required for type `BUTTONS`.** Buttons are optional interactive components that perform specific actions when tapped. Templates can have a mixture of up to 10 button components total, although there are limits to individual buttons of the same type as well as combination limits. If a template has more than three buttons, two buttons will appear in the delivered message and the remaining buttons will be replaced with a **See all options** button. Tapping the **See all options** button reveals the remaining buttons.
     * @type {Array<WhatsappTemplateComponentButton>}
     * @memberof WhatsappTemplateComponent
     */
    'buttons'?: Array<WhatsappTemplateComponentButton>;
    /**
     * **Optional. Only applicable in the `BODY` component of an AUTHENTICATION template.** Set to `true` if you want the template to include the string, *For your security, do not share this code.* Set to `false` to exclude the string.
     * @type {boolean}
     * @memberof WhatsappTemplateComponent
     */
    'add_security_recommendation'?: boolean;
    /**
     * **Optional. Only applicable in the `FOOTER` component of an AUTHENTICATION template.** Indicates number of minutes the password or code is valid. If omitted, the code expiration warning will not be displayed in the delivered message. Minimum 1, maximum 90.
     * @type {number}
     * @memberof WhatsappTemplateComponent
     */
    'code_expiration_minutes'?: number;
    /**
     * 
     * @type {WhatsappTemplateComponentLimitedTimeOffer}
     * @memberof WhatsappTemplateComponent
     */
    'limited_time_offer'?: WhatsappTemplateComponentLimitedTimeOffer;
    /**
     * 
     * @type {WhatsappTemplateComponentExample}
     * @memberof WhatsappTemplateComponent
     */
    'example'?: WhatsappTemplateComponentExample;
    /**
     * **Required for type `CAROUSEL`.** Carousel templates support up to 10 carousel cards.
     * @type {Array<WhatsappTemplateComponentCard>}
     * @memberof WhatsappTemplateComponent
     */
    'cards'?: Array<WhatsappTemplateComponentCard>;
}

export const WhatsappTemplateComponentTypeEnum = {
    Body: 'BODY',
    Header: 'HEADER',
    Footer: 'FOOTER',
    Buttons: 'BUTTONS',
    LimitedTimeOffer: 'LIMITED_TIME_OFFER',
    Carousel: 'CAROUSEL'
} as const;

export type WhatsappTemplateComponentTypeEnum = typeof WhatsappTemplateComponentTypeEnum[keyof typeof WhatsappTemplateComponentTypeEnum];
export const WhatsappTemplateComponentFormatEnum = {
    Text: 'TEXT',
    Image: 'IMAGE',
    Video: 'VIDEO',
    Document: 'DOCUMENT',
    Location: 'LOCATION'
} as const;

export type WhatsappTemplateComponentFormatEnum = typeof WhatsappTemplateComponentFormatEnum[keyof typeof WhatsappTemplateComponentFormatEnum];


