/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Full contact name formatted as a name object.
 * @export
 * @interface WhatsappMessageContactName
 */
export interface WhatsappMessageContactName {
    /**
     * Full name, as it normally appears.
     * @type {string}
     * @memberof WhatsappMessageContactName
     */
    'formatted_name': string;
    /**
     * First name.
     * @type {string}
     * @memberof WhatsappMessageContactName
     */
    'first_name'?: string;
    /**
     * Last name.
     * @type {string}
     * @memberof WhatsappMessageContactName
     */
    'last_name'?: string;
    /**
     * Middle name.
     * @type {string}
     * @memberof WhatsappMessageContactName
     */
    'middle_name'?: string;
    /**
     * Name suffix.
     * @type {string}
     * @memberof WhatsappMessageContactName
     */
    'suffix'?: string;
    /**
     * Name prefix.
     * @type {string}
     * @memberof WhatsappMessageContactName
     */
    'prefix'?: string;
}

