/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WhatsappCallingConnectRequest
 */
export interface WhatsappCallingConnectRequest {
    /**
     * The caller\'s phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.
     * @type {string}
     * @memberof WhatsappCallingConnectRequest
     */
    'from': string;
    /**
     * The callee\'s phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.
     * @type {string}
     * @memberof WhatsappCallingConnectRequest
     */
    'to': string;
    /**
     * The SDP type, must be \"offer\" for connection requests.
     * @type {string}
     * @memberof WhatsappCallingConnectRequest
     */
    'sdpType': WhatsappCallingConnectRequestSdpTypeEnum;
    /**
     * The Session Description Protocol (SDP) offer information compliant with [RFC 8866](https://datatracker.ietf.org/doc/html/rfc8866). Contains media session parameters for establishing the WebRTC connection.
     * @type {string}
     * @memberof WhatsappCallingConnectRequest
     */
    'sdp': string;
}

export const WhatsappCallingConnectRequestSdpTypeEnum = {
    Offer: 'offer'
} as const;

export type WhatsappCallingConnectRequestSdpTypeEnum = typeof WhatsappCallingConnectRequestSdpTypeEnum[keyof typeof WhatsappCallingConnectRequestSdpTypeEnum];


