/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * WhatsApp business phone number\'s commerce settings.
 * @export
 * @interface WhatsappCommerceSettings
 */
export interface WhatsappCommerceSettings {
    /**
     * Unique ID for the object.
     * @type {string}
     * @memberof WhatsappCommerceSettings
     */
    'id'?: string;
    /**
     * When enabled, cart-related buttons appear in the conversation, catalog, and product details views. When the cart is disabled, customers can see products and their details, but all cart related buttons will not appear in any view.
     * @type {boolean}
     * @memberof WhatsappCommerceSettings
     */
    'isCartEnabled'?: boolean;
    /**
     * When enabled, the catalog storefront icon and catalog-related buttons appear in conversation and business profile views. When the catalog is disabled, the storefront icon and catalog-related buttons will not appear in any views and the catalog preview with thumbnails will not appear in the business profile view.
     * @type {boolean}
     * @memberof WhatsappCommerceSettings
     */
    'isCatalogVisible'?: boolean;
}

