/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Group setting update detail.
 * @export
 * @interface WhatsappGroupWebhookSetting
 */
export interface WhatsappGroupWebhookSetting {
    /**
     * Setting name.
     * @type {string}
     * @memberof WhatsappGroupWebhookSetting
     */
    'name'?: WhatsappGroupWebhookSettingNameEnum;
    /**
     * Text value for subject or description updates.
     * @type {string}
     * @memberof WhatsappGroupWebhookSetting
     */
    'text'?: string;
    /**
     * Whether the setting update succeeded.
     * @type {boolean}
     * @memberof WhatsappGroupWebhookSetting
     */
    'updateSuccessful'?: boolean;
    /**
     * MIME type for profile picture updates.
     * @type {string}
     * @memberof WhatsappGroupWebhookSetting
     */
    'mimeType'?: string;
    /**
     * SHA-256 hash for profile picture updates.
     * @type {string}
     * @memberof WhatsappGroupWebhookSetting
     */
    'sha256'?: string;
    /**
     * Errors returned by WhatsApp for this setting.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof WhatsappGroupWebhookSetting
     */
    'errors'?: Array<{ [key: string]: any; }>;
}

export const WhatsappGroupWebhookSettingNameEnum = {
    ProfilePicture: 'profile_picture',
    GroupSubject: 'group_subject',
    GroupDescription: 'group_description'
} as const;

export type WhatsappGroupWebhookSettingNameEnum = typeof WhatsappGroupWebhookSettingNameEnum[keyof typeof WhatsappGroupWebhookSettingNameEnum];


