/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Optional for card.
 * @export
 * @interface WhatsappMessageInteractiveActionCardBody
 */
export interface WhatsappMessageInteractiveActionCardBody {
    /**
     * Max 160 chars, and up to 2 line breaks.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionCardBody
     */
    'text'?: string;
}

