/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappFlowCategory } from './whatsapp-flow-category';
import { WhatsappFlowStatus } from './whatsapp-flow-status';
import { WhatsappFlowValidationError } from './whatsapp-flow-validation-error';

/**
 * Represents a list item of WhatsApp Flows.
 * @export
 * @interface WhatsappListFlowItem
 */
export interface WhatsappListFlowItem {
    /**
     * Flow ID.
     * @type {string}
     * @memberof WhatsappListFlowItem
     */
    'id'?: string;
    /**
     * Flow name.
     * @type {string}
     * @memberof WhatsappListFlowItem
     */
    'name'?: string;
    /**
     * 
     * @type {WhatsappFlowStatus}
     * @memberof WhatsappListFlowItem
     */
    'status'?: WhatsappFlowStatus;
    /**
     * Flow categories.
     * @type {Array<WhatsappFlowCategory>}
     * @memberof WhatsappListFlowItem
     */
    'categories'?: Array<WhatsappFlowCategory>;
    /**
     * List of validation errors.
     * @type {Array<WhatsappFlowValidationError>}
     * @memberof WhatsappListFlowItem
     */
    'validationErrors'?: Array<WhatsappFlowValidationError>;
}

