/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageInteractiveActionCardActionButton } from './whatsapp-message-interactive-action-card-action-button';
import { WhatsappMessageInteractiveActionCardActionParameters } from './whatsapp-message-interactive-action-card-action-parameters';

/**
 * A button object in `interactive` messages. Cards must include either one URL button, or one or more quick-reply buttons. Button types and numbers must match across all cards (for example, if you define a card with 2 quick-reply buttons, all cards must define exactly 2 quick-reply buttons).
 * @export
 * @interface WhatsappMessageInteractiveActionCardAction
 */
export interface WhatsappMessageInteractiveActionCardAction {
    /**
     * Required when card action is url button. Must be \"cta_url\".
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionCardAction
     */
    'name'?: string;
    /**
     *
     * @type {WhatsappMessageInteractiveActionCardActionParameters}
     * @memberof WhatsappMessageInteractiveActionCardAction
     */
    'parameters'?: WhatsappMessageInteractiveActionCardActionParameters;
    /**
     * Required when card action is quick reply button.
     * @type {Array<WhatsappMessageInteractiveActionCardActionButton>}
     * @memberof WhatsappMessageInteractiveActionCardAction
     */
    'buttons'?: Array<WhatsappMessageInteractiveActionCardActionButton>;
}

