/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Action parameters. Required for Call-To-Action (CTA) URL Button Messages.
 * @export
 * @interface WhatsappMessageInteractiveActionParameters
 */
export interface WhatsappMessageInteractiveActionParameters {
    /**
     * Text of the CTA URL button. Maximum length: 20 bytes.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionParameters
     */
    'display_text'?: string;
    /**
     * URL of the CTA URL button.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionParameters
     */
    'url'?: string;
    /**
     * Item SKU number. Labeled as **Content ID** in the [Commerce Manager](https://business.facebook.com/commerce). The thumbnail of this item will be used as the message\'s header image.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionParameters
     */
    'thumbnail_product_retailer_id'?: string;
}

