/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Status of the WhatsApp Flow. - `DRAFT`: The Flow is in draft state and can be modified. - `PUBLISHED`: The Flow is published and cannot be modified. - `DEPRECATED`: The Flow is deprecated and cannot be used.
 * @export
 * @enum {string}
 */

export const WhatsappFlowStatus = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Deprecated: 'DEPRECATED'
} as const;

export type WhatsappFlowStatus = typeof WhatsappFlowStatus[keyof typeof WhatsappFlowStatus];



