/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WhatsappMessageContactPhone
 */
export interface WhatsappMessageContactPhone {
    /**
     * Automatically populated with the `wa_id` value as a formatted phone number.
     * @type {string}
     * @memberof WhatsappMessageContactPhone
     */
    'phone'?: string;
    /**
     * Standard Values are `CELL`, `MAIN`, `IPHONE`, `HOME`, and `WORK`.
     * @type {string}
     * @memberof WhatsappMessageContactPhone
     */
    'type'?: string;
    /**
     * WhatsApp ID.
     * @type {string}
     * @memberof WhatsappMessageContactPhone
     */
    'wa_id'?: string;
}

