/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents a WhatsApp media object that has been uploaded via the media upload API.
 * @export
 * @interface WhatsappMedia
 */
export interface WhatsappMedia {
    /**
     * Unique identifier for the uploaded media. This ID can be used in subsequent message requests.
     * @type {string}
     * @memberof WhatsappMedia
     */
    'id'?: string;
}

