/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * WhatsApp inbound message type. See also [WhatsApp webhook messages object](https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks/components#messages-object).
 * @export
 * @enum {string}
 */

export const WhatsappInboundMessageType = {
    Text: 'text',
    Image: 'image',
    Video: 'video',
    Audio: 'audio',
    Document: 'document',
    Sticker: 'sticker',
    Contacts: 'contacts',
    Location: 'location',
    Interactive: 'interactive',
    Button: 'button',
    System: 'system',
    Unknown: 'unknown'
} as const;

export type WhatsappInboundMessageType = typeof WhatsappInboundMessageType[keyof typeof WhatsappInboundMessageType];



