/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Additional info for BillDesk. User-defined fields (extra) are used to store any information corresponding to a particular order. Each extra field has a maximum character limit of 120.
 * @export
 * @interface WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk
 */
export interface WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk {
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk
     */
    'additional_info1'?: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk
     */
    'additional_info2'?: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk
     */
    'additional_info3'?: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk
     */
    'additional_info4'?: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk
     */
    'additional_info5'?: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk
     */
    'additional_info6'?: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayBilldesk
     */
    'additional_info7'?: string;
}

