/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Additional info for Zaakpay. User-defined fields (extra) are used to store any information corresponding to a particular order. Each extra field has a maximum character limit of 180.
 * @export
 * @interface WhatsappMessageOrderPaymentSettingPaymentGatewayZaakpay
 */
export interface WhatsappMessageOrderPaymentSettingPaymentGatewayZaakpay {
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayZaakpay
     */
    'extra1'?: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayZaakpay
     */
    'extra2'?: string;
}

