/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Additional info for PayU. User-defined fields (udf) are used to store any information corresponding to a particular order. Each UDF field has a maximum character limit of 255.
 * @export
 * @interface WhatsappMessageOrderPaymentSettingPaymentGatewayPayu
 */
export interface WhatsappMessageOrderPaymentSettingPaymentGatewayPayu {
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayPayu
     */
    'udf1'?: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayPayu
     */
    'udf2'?: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayPayu
     */
    'udf3'?: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsappMessageOrderPaymentSettingPaymentGatewayPayu
     */
    'udf4'?: string;
}

