/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageTemplateComponentParameterActionSection } from './whatsapp-message-template-component-parameter-action-section';

/**
 * Required if template uses catalog or MPM (multi-product message) buttons.
 * @export
 * @interface WhatsappMessageTemplateComponentParameterAction
 */
export interface WhatsappMessageTemplateComponentParameterAction {
    /**
     * **Optional.** Use for catalog and MPM template messages. Item SKU number. Labeled as Content ID in the Commerce Manager. The thumbnail of this item will be used as the message\'s header image. If the `parameters` object is omitted, the product image of the first item in your catalog will be used.
     * @type {string}
     * @memberof WhatsappMessageTemplateComponentParameterAction
     */
    'thumbnail_product_retailer_id'?: string;
    /**
     * Use for MPM templates. Product sections. You can define up to 10 sections.
     * @type {Array<WhatsappMessageTemplateComponentParameterActionSection>}
     * @memberof WhatsappMessageTemplateComponentParameterAction
     */
    'sections'?: Array<WhatsappMessageTemplateComponentParameterActionSection>;
}

