/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageContact } from './whatsapp-message-contact';
import { WhatsappMessageContext } from './whatsapp-message-context';
import { WhatsappMessageInteractive } from './whatsapp-message-interactive';
import { WhatsappMessageLocation } from './whatsapp-message-location';
import { WhatsappMessageMedia } from './whatsapp-message-media';
import { WhatsappMessageReaction } from './whatsapp-message-reaction';
import { WhatsappMessageTemplate } from './whatsapp-message-template';
import { WhatsappMessageText } from './whatsapp-message-text';
import { WhatsappMessageType } from './whatsapp-message-type';

/**
 * 
 * @export
 * @interface WhatsappMessageSendRequest
 */
export interface WhatsappMessageSendRequest {
    /**
     * The sender\'s phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.
     * @type {string}
     * @memberof WhatsappMessageSendRequest
     */
    'from': string;
    /**
     * The recipient\'s phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.
     * @type {string}
     * @memberof WhatsappMessageSendRequest
     */
    'to': string;
    /**
     * 
     * @type {WhatsappMessageType}
     * @memberof WhatsappMessageSendRequest
     */
    'type': WhatsappMessageType;
    /**
     * 
     * @type {WhatsappMessageTemplate}
     * @memberof WhatsappMessageSendRequest
     */
    'template'?: WhatsappMessageTemplate;
    /**
     * 
     * @type {WhatsappMessageText}
     * @memberof WhatsappMessageSendRequest
     */
    'text'?: WhatsappMessageText;
    /**
     * 
     * @type {WhatsappMessageMedia}
     * @memberof WhatsappMessageSendRequest
     */
    'image'?: WhatsappMessageMedia;
    /**
     * 
     * @type {WhatsappMessageMedia}
     * @memberof WhatsappMessageSendRequest
     */
    'video'?: WhatsappMessageMedia;
    /**
     * 
     * @type {WhatsappMessageMedia}
     * @memberof WhatsappMessageSendRequest
     */
    'audio'?: WhatsappMessageMedia;
    /**
     * 
     * @type {WhatsappMessageMedia}
     * @memberof WhatsappMessageSendRequest
     */
    'document'?: WhatsappMessageMedia;
    /**
     * 
     * @type {WhatsappMessageMedia}
     * @memberof WhatsappMessageSendRequest
     */
    'sticker'?: WhatsappMessageMedia;
    /**
     * 
     * @type {WhatsappMessageLocation}
     * @memberof WhatsappMessageSendRequest
     */
    'location'?: WhatsappMessageLocation;
    /**
     * 
     * @type {WhatsappMessageInteractive}
     * @memberof WhatsappMessageSendRequest
     */
    'interactive'?: WhatsappMessageInteractive;
    /**
     * Required when `type` is `contacts`.
     * @type {Array<WhatsappMessageContact>}
     * @memberof WhatsappMessageSendRequest
     */
    'contacts'?: Array<WhatsappMessageContact>;
    /**
     * 
     * @type {WhatsappMessageReaction}
     * @memberof WhatsappMessageSendRequest
     */
    'reaction'?: WhatsappMessageReaction;
    /**
     * 
     * @type {WhatsappMessageContext}
     * @memberof WhatsappMessageSendRequest
     */
    'context'?: WhatsappMessageContext;
    /**
     * A unique (recommended) string to reference the object. This can be an order number or similar, and can be used to reconcile the object with your internal systems.
     * @type {string}
     * @memberof WhatsappMessageSendRequest
     */
    'externalId'?: string;
    /**
     * **Optional.** If set to `true`, the message will not be sent to users who have unsubscribed from your account. Defaults to `false`.  Only use for `POST /v2/whatsapp/messages`. If the user has unsubscribed, we will push webhook notifications with `whatsappMessage.errorCode` set to `RECIPIENT_UNSUBSCRIBED`.  Not applicable to `POST /v2/whatsapp/message/sendDirectly`.
     * @type {boolean}
     * @memberof WhatsappMessageSendRequest
     */
    'filterUnsubscribed'?: boolean;
    /**
     * **Optional.** If set to `true`, the message will not be sent to users in your block list. Defaults to `false`.  Only use for `POST /v2/whatsapp/messages`. If the user is in your block list, we will push webhook notifications with `whatsappMessage.errorCode` set to `RECIPIENT_IN_BLOCK_LIST`.  Not applicable to `POST /v2/whatsapp/message/sendDirectly`.
     * @type {boolean}
     * @memberof WhatsappMessageSendRequest
     */
    'filterBlocked'?: boolean;
}

