/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { WhatsappMessageInteractiveActionSectionsInnerRowsInner } from './whatsapp-message-interactive-action-sections-inner-rows-inner';

/**
 * [WhatsApp Section Object](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#section-object).
 * @export
 * @interface WhatsappMessageInteractiveActionSectionsInner
 */
export interface WhatsappMessageInteractiveActionSectionsInner {
    /**
     * Title of the section.
     * @type {string}
     * @memberof WhatsappMessageInteractiveActionSectionsInner
     */
    'title'?: string;
    /**
     * Contains a list of rows. You can have a total of 10 rows across your sections. Each row must have a title (Maximum length: 24 characters) and an ID (Maximum length: 200 characters). You can add a description (Maximum length: 72 characters), but it is optional.
     * @type {Array<WhatsappMessageInteractiveActionSectionsInnerRowsInner>}
     * @memberof WhatsappMessageInteractiveActionSectionsInner
     */
    'rows'?: Array<WhatsappMessageInteractiveActionSectionsInnerRowsInner>;
}

