/* tslint:disable */
/* eslint-disable */
/**
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A Product Enquiry Message is received when a user is asking for more information about a specific product. These can be received as in two scenarios: 1. When a customer replies to Single or Multi-Product Messages. 2. When a customer accesses a business’ catalog through another entry point, navigates to a Product Details Page, and clicks Message Business about this Product.
 * @export
 * @interface WhatsappInboundMessageReferredProduct
 */
export interface WhatsappInboundMessageReferredProduct {
    /**
     * The catalog ID.
     * @type {string}
     * @memberof WhatsappInboundMessageReferredProduct
     */
    'catalog_id'?: string;
    /**
     * The product SKU identifier.
     * @type {string}
     * @memberof WhatsappInboundMessageReferredProduct
     */
    'product_retailer_id'?: string;
}

